# Generated by Django 2.0 on 2017-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=200)),
                ('Age', models.PositiveSmallIntegerField(default=0)),
                ('Breed', models.CharField(max_length=500)),
                ('Color', models.CharField(max_length=100)),
            ],
        ),
    ]
