# Generated by Django 2.0 on 2017-12-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bunny',
            new_name='Rabbit',
        ),
    ]
